--- #YAML:1.0
name:               Redis-DistLock
version:            0.07
abstract:           Distributed lock manager using Redis
author:
    - Simon Bertrang <janus@cpan.org>, Ryan Bastic <ryan@bastic.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::SHA:   0
    MIME::Base64:  0
    Redis:         0
    Time::HiRes:   0
resources:
    bugtracker:  https://github.com/sbertrang/redis-distlock/issues
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/sbertrang/redis-distlock
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
